server:
  port: 8090
  tomcat:
    max-connections: 3000
spring:
  application:
    name: expay-websocket
  profiles:
    active: ${env:dev}
  rabbitmq:
    sys:
      host: 127.0.0.1
      port: 15672
      username: guest
      password: guest
      listener:
        simple:
          acknowledge-mode: auto
          retry:
            enabled: true
            max-attempts: 5
            initial-interval: 10000
      publisher-returns: true
      publisher-confirm-type: correlated
  redis:
    host: 127.0.0.1
    port: 6379
    password:
logging:
  config:
  level:
    root: info